/**********************************************************************  Filename:  throw2.cpp  Chapter:   9      Exceptions  Compiler:  Borland C++     Version 5.01      Summer 1998  C++ for C Programmers, Edition 3     By Ira Pohl********************************************************************/#include <iostream>#include <stdlib>//using namespace std;void foo(){   int  i, j;   i = 14;   j = 15;   throw i;}void call_foo(){   int  k;   k = 12;   foo();}int main(){   try {      call_foo();       //foo exits with i and j destroyed   }   catch(int n) { cout << "\ncaught it " << n << endl; }   int look; cin >> look;}